### ISSUE TITLE
RSS 버튼이 동작하지 않습니다.

### ISSUE THREAD

**Issue by BenjaminKim** [justiceHui/justiceHui.github.io#94]
블로그 너무 멋집니다.
[RSS가](https://justicehui.github.io/atom.xml) 제대로 동작하지 않네요.
구독해서 열심히 읽어보고 싶습니다!

**Comment by justiceHui** [comment]
sidebar에 있는 rss 링크를 수정했습니다. rss feed는 [https://justicehui.github.io/rss/](https://justicehui.github.io/rss/)에서도 확인할 수 있습니다. 이슈 남겨주셔서 감사합니다.
